# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-21 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WWCapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('donorInfo', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='item',
            new_name='itemName',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='requestId',
            new_name='requestorInfo',
        ),
        migrations.RemoveField(
            model_name='requests',
            name='userId',
        ),
    ]
